export const siteConfig = {
  name: "San Jose Siding Pros",
  description: "Premium siding replacement, repair, and installation for homeowners across Silicon Valley.",
  url: process.env.SITE_URL ?? "http://localhost:3000",
  phone: "(408) 555-0199",
  email: "info@sanjosesidingpros.com",
  address: "1234 Alum Rock Ave, San Jose, CA 95116",
  logo: "/logo.svg",
  social: {
    facebook: "https://facebook.com/sanjosesidingpros",
    instagram: "https://instagram.com/sanjosesidingpros",
    linkedin: "https://linkedin.com/company/sanjose-siding-pros",
  },
  nav: [
    { title: "Home", href: "/" },
    { title: "About", href: "/about" },
    {
      title: "Services",
      href: "/services",
      children: [
        { title: "Vinyl Siding", href: "/services/vinyl-siding" },
        { title: "Fiber Cement", href: "/services/fiber-cement-siding" },
        { title: "Wood Siding", href: "/services/wood-siding" },
        { title: "Siding Repair", href: "/services/siding-repair" },
        { title: "Replacement", href: "/services/siding-replacement" },
        { title: "Emergency", href: "/services/emergency-siding" },
      ],
    },
    { title: "Service Area", href: "/service-areas/san-jose" },
    { title: "Gallery", href: "/gallery" },
    { title: "Blog", href: "/blog" },
    { title: "FAQ", href: "/faq" },
    { title: "Contact", href: "/contact" },
  ],
};
